sudo: required
env:
  - SPEC_PATH=$(pwd)
services:
  - docker
before_install:
  - docker pull slate/swagger-spec-validator
  - docker pull lezsakdomi/capnproto-cplusplus
script:
  - docker run -it -e "SPEC_PATH=$SPEC_PATH" -v $SPEC_PATH:/data --name spec-validator slate/swagger-spec-validator:latest
  - docker logs $(docker ps -lq)
  - docker run --rm -v ${SPEC_PATH}:/tmp lezsakdomi/capnproto-cplusplus capnp compile -oc++ /tmp/tiledb-rest.capnp
