sudo: required
env:
  - SPEC_PATH=$(pwd)
services:
  - docker
before_install:
  - docker pull node
script:
  - docker run -it --volume ${PWD}/openapi-v1.yaml:/spec/openapi.yaml node /bin/bash -c 'npm install --save swagger-cli && ./node_modules/swagger-cli/swagger-cli.js validate /spec/openapi.yaml'
  - docker logs $(docker ps -lq)
  - docker run -it --volume ${PWD}/openapi-v2.yaml:/spec/openapi.yaml node /bin/bash -c 'npm install --save swagger-cli && ./node_modules/swagger-cli/swagger-cli.js validate /spec/openapi.yaml'
  - docker logs $(docker ps -lq)
